### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by rjmk**
I noticed that the docs don't always reflect the latest APIs. I started updating the reconciliation section to use the new `View` API, but then I realised that the section on strict data is not actually accurate any more. At least I believe so, am I correct?

I also added some overall documentation from the old ReactViews API to the Views API

### CODE REVIEW

**Comment by fisx** [comment]
Great you're working on this!  I started #24 a while back, but haven't finished it yet, so this is very much appreciated.  I'm a bit tied up this week, but I'll look into it soon.

thanks~

**Comment by rjmk** [comment]
Don't know how I missed #24 -- that's definitely got better docs for the performance section

**Comment by fisx** [comment]
Obsoleted by #43.  (I used your changes there, thanks!)

**Comment by rjmk** [comment]
Awesome, thanks 👍

**Pull request closed without merging**
