### PR TITLE
Rename someStoreAction to just action

### PR DESCRIPTION
**Pull request by tysonzero**

### CODE REVIEW

**Comment by tysonzero** [comment]
https://github.com/liqula/react-hs/issues/30

**Comment by fisx** [comment]
LGTM!

If you fix the name shadowing issue I'll merge.

**Comment by tysonzero** [comment]
Should be ok now?

**Comment by fisx** [comment]
another one...  that's why i like non-trivial names.  (-:

**Comment by tysonzero** [comment]
Haha fair enough, although wait a minute, those errors are in react-hs-examples, which I didn't touch. Does react-hs-examples just hot-link straight into the local react-hs? IMO that is not worth it, it should depend on a real version of react-hs that people can/will actually use, that way the examples are exactly what an end user will mimic.

**Comment by tysonzero** [comment]
Alright, will sort that out! And sorry about the close / reopen, misclicked. So I guess react-sh-examples hotlinks straight into the local react-hs?

**Comment by fisx** [comment]
> So I guess react-sh-examples hotlinks straight into the local react-hs?

Yes.  The advantage is that you can develop react-hs and react-hs-examples concurrently.  I admit that it's a bit weird, especially if you can `cabal unpack` it straight from hackage.  But without this I wouldn't have caught your mistake and it would have gone to hackage broken, which is also bad, so I would prefer to accept this weirdness for now.

**Comment by fisx** [comment]
Thanks!

**Pull request merged**
