### PR TITLE
Make props be a single argument

### PR DESCRIPTION
**Pull request by tysonzero**
Props is now a single argument and type level lists are no longer needed for dealing with props, as per #70.

The one remaining thing is that props is still passed in through a list, that list just always has length 1, as I'm not very familiar with all the different hs-js interop going on. Doing it this way made the change pretty much entirely verified by the compiler and all the not-verified stuff was relatively simple.

I am happy to next work on converting to truly passing in one argument on the JS level, but will take some time, and I'm worried I will miss something and the compiler won't catch it, anyone else who wants to do that is more than welcome to.

### CODE REVIEW

**Comment by tysonzero** [comment]
Will fix the travis stuff now.

**Comment by fisx** [comment]
Thanks a lot, I'm going to test this on our code as soon as I can find the time.

I agree that it's better to keep the list intact and avoid having to debug the marshaling code (which I think is still buggy to begin with).  As soon as I've confirmed that our code base still works, I will merge this. 

(Until then, any feedback from other users is appreciated!)

**Comment by tysonzero** [comment]
Sounds great!

In the long run we probably should look at the marshaling code, but for now this should be fine.

**Comment by tysonzero** [comment]
Any updates?

**Comment by fisx** [comment]
sorry, but we won't be able to test this for at least another week.

i have updated the README section with an explanation what "experimental" means.  given that i've asked for this PR, i really want to merge it of course, but i need to find an hour or two first to build or codebase against it, and probably do some minor refactoring.  i haven't forgotten you!

**Comment by rjmk** [comment]
So I built our project with this branch and it works fine. I would say the fact that controller views haven't changed made things a little surprising.

I realise it would be a bit annoying to define, for example, `ControllerViewStores` for various tuples, but I think that would be more in keeping with this approach

**Comment by tysonzero** [comment]
I currently have left controller views alone due to the fact that if you do the same change for controller views you will not be able to have one view directly depend on multiple stores, so you'll have to layer some helper views and build up all the store values in props.

**Comment by rjmk** [comment]
I meant keeping the list of types (`forall stores :: [*]`), but only passing in a single argument (instead of ControllerViewToElement). Thinking about it though, that might not work. I wonder whether with some tweaking something like that could be made to work

**Comment by tysonzero** [comment]
What would that single argument be? Perhaps a heterogenous list? Tuples won't work as you can't really do `cons` or similar on a tuple, an n-tuple and an (n+1)-tuple are unrelated types.

**Comment by rjmk** [comment]
On my work laptop I have something with tuples that was, if not working, looking promising. You do need separate instances for `ControllerViewStores` for 2-tuples, 3-tuples, etc. I think that might be acceptable cruft

**Comment by tysonzero** [comment]
I personally would consider that very ugly, it disobeys the zero one infinity rule, and it is quite a lot of cruft. I'd be ok with heterogenous lists, but hacking it onto tuples is IMO worse than the current solution and really doesn't buy us much.

**Comment by rjmk** [comment]
I suppose it is uglier. It has some precedent though. For example, the tuple lenses in `lens`.

The advantage I see is that it makes the API less surprising.

Not worth blocking this PR over though

**Comment by tysonzero** [comment]
What is the status on this, is it alright for me to merge it once I resolve the conflicts?

**Comment by tysonzero** [comment]
@fisx I do think this will be beneficial overall and a fairly needed change in the long run. But I am aware it is very backwards incompatible, so I would prefer to wait for confirmation from you before resolving the merge conflict and merging this.

**Comment by fisx** [comment]
you have my blessing.  :-)

I remember having taken a quick look earlier and agreeing with the change at least in theory.

thanks!

**Comment by dbaynard** [comment]
To be clear, types are still first class here, so it's possible to supply a record of arguments? And the difference in output javascript: do a two-element record and a two-tuple result in the same javascript?

**Comment by tysonzero** [comment]
You can supply tuples or records or anything you want for sure. And there should be no difference between a two-tuple and a two-element record, just like with GHC.

**Pull request merged**
