### PR TITLE
Add lambda example

### PR DESCRIPTION
**Pull request by aische**
Here's the lambda interpreter example.

### CODE REVIEW

**Comment by fisx** [comment]
Cool!  (-:

- could you make the same change here that i just did in #61, https://github.com/liqula/react-hs/pull/61/commits/4961a2fe840b5d0ac26d7c87fa9c2024ca817537?
- could you rename the directory to react-hs-examples/lambda?

**Comment by fisx** [comment]
Thanks!

**Comment by fisx** [comment]
(My comment about `/scripts/build.sh` was stupid: you didn't need that because you used the pattern that also worked in the todo example.  Sorry for the confusion, I fixed it locally.)

**Comment by aische** [comment]
Great! Thanks for merging!

**Pull request merged**
