### PR TITLE
Add `label` parameter to Term typeclass

### PR DESCRIPTION
**Pull request by rjmk**
Hey! We're finding this fork very useful at NStack. I like not having to add in the empty lists of properties, but unfortunately can't get that nicety with foreign classes. With this tweak, I can newtype JSString and use the foreign classes with the same slickness.

### CODE REVIEW

**Comment by fisx** [comment]
Thanks, I like this change.  Two questions:

1. I don't quite understand what you are using this for.  Could you add a paragraph and a bit of example code to the module docs?
2. Would you like remove the commented-out code with the CPP generator?  (Admittedly this has nothing to do with your change, but I've just noticed this now.)

If you answer both questions with "no, thanks", I can still merge.  Just let me know.

**Comment by rjmk** [comment]
Done. Let me know if there's anything else. :)

**Comment by fisx** [comment]
Perfect!  Thanks!  :-)

(If you want to do more #25 is about to get merged, and it will make smal changes to the interface.  Any feedback appreciated.)

**Comment by fisx** [comment]
Erm, did I just break master now?  Sorry, I have to go, but I'll look into it before the end of the day (CEST).

**Comment by rjmk** [comment]
Broken how? I have a project building off my branch that seems OK.

Also, will have a look at the PR

**Comment by fisx** [comment]
Ah, never mind.  rebasing is confusing!  (-:

**Comment by fisx** [comment]
> Broken how? I have a project building off my branch that seems OK.

not broken.  i was just reading the diff wrong.  sorry for the noise.

**Pull request merged**
